"""Add login and password fields to external_integrations

Revision ID: 018_add_login_password_external_integrations
Revises: 017_add_external_integrations
Create Date: 2025-08-26 19:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018_add_login_password_external_integrations'
down_revision = ['016_add_account_balances', '017_add_external_integrations']
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_integrations', sa.Column('login_encrypted', sa.Text(), nullable=True))
    op.add_column('external_integrations', sa.Column('password_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_integrations', 'password_encrypted')
    op.drop_column('external_integrations', 'login_encrypted')
    # ### end Alembic commands ###