"""Add description_norm field

Revision ID: cb30983c8466
Revises: 002
Create Date: 2025-08-17 13:17:14.331722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb30983c8466'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_plaid_account_id', table_name='accounts')
    op.create_index(op.f('ix_accounts_plaid_account_id'), 'accounts', ['plaid_account_id'], unique=True)
    op.drop_index('ix_institution_items_plaid_item_id', table_name='institution_items')
    op.create_index(op.f('ix_institution_items_plaid_item_id'), 'institution_items', ['plaid_item_id'], unique=True)
    op.add_column('transactions', sa.Column('description_norm', sa.String(length=255), nullable=True))
    op.drop_index('ix_transactions_plaid_transaction_id', table_name='transactions')
    op.create_index(op.f('ix_transactions_plaid_transaction_id'), 'transactions', ['plaid_transaction_id'], unique=True)
    op.create_index(op.f('ix_transactions_description_norm'), 'transactions', ['description_norm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_description_norm'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_plaid_transaction_id'), table_name='transactions')
    op.create_index('ix_transactions_plaid_transaction_id', 'transactions', ['plaid_transaction_id'], unique=False)
    op.drop_column('transactions', 'description_norm')
    op.drop_index(op.f('ix_institution_items_plaid_item_id'), table_name='institution_items')
    op.create_index('ix_institution_items_plaid_item_id', 'institution_items', ['plaid_item_id'], unique=False)
    op.drop_index(op.f('ix_accounts_plaid_account_id'), table_name='accounts')
    op.create_index('ix_accounts_plaid_account_id', 'accounts', ['plaid_account_id'], unique=False)
    # ### end Alembic commands ###

