"""Extend MerchantRule for 2-level mapping

Revision ID: fae2d81a9c34
Revises: cb30983c8466
Create Date: 2025-08-17 13:18:54.366428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae2d81a9c34'
down_revision = 'cb30983c8466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_rules', sa.Column('fields', sa.Enum('MERCHANT', 'DESCRIPTION', 'PAIR', name='rulefields'), nullable=False, server_default='MERCHANT'))
    op.add_column('merchant_rules', sa.Column('desc_pattern', sa.String(length=500), nullable=True))
    op.add_column('merchant_rules', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    # Skip foreign key constraint for SQLite
    # op.create_foreign_key(None, 'merchant_rules', 'categories', ['subcategory_id'], ['id'])
    op.drop_column('merchant_rules', 'merchant_norm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_rules', sa.Column('merchant_norm', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'merchant_rules', type_='foreignkey')
    op.drop_column('merchant_rules', 'subcategory_id')
    op.drop_column('merchant_rules', 'desc_pattern')
    op.drop_column('merchant_rules', 'fields')
    # ### end Alembic commands ###

